[[redirects]]
  from = "/api/*"
  to = "https://fullnode.devnet.aptoslabs.com/:splat"
  status = 200

  [[redirects]]
  from = "/faucet/*"
  to = "https://faucet.devnet.aptoslabs.com/:splat"
  status = 200